// Generated by wrangler types command
// Run: npm run cf-typegen

import type { Sandbox } from '@cloudflare/sandbox';

declare global {
  interface Env {
    // KV Namespaces
    AUTH_KV: KVNamespace;
    SESSIONS_KV: KVNamespace;

    // R2 Buckets
    FILES_BUCKET: R2Bucket;

    // Durable Objects
    SESSIONS: DurableObjectNamespace;

    // Containers (Sandboxes) - typed for @cloudflare/sandbox SDK
    SANDBOX_CONTAINER: DurableObjectNamespace<Sandbox>;

    // Secrets (set via wrangler secret put)
    CLAUDE_API_KEY?: string;
    CLAUDE_CLIENT_ID?: string;
    CLAUDE_CLIENT_SECRET?: string;
    JWT_SECRET: string;

    // Environment variables
    ENVIRONMENT: string;
  }
}

export {};
