// Generated by wrangler types command
// Run: npm run cf-typegen

interface Env {
  // KV Namespaces
  AUTH_KV: KVNamespace;
  SESSIONS_KV: KVNamespace;

  // R2 Buckets (optional - enable R2 in dashboard first)
  FILES_BUCKET?: R2Bucket;

  // Durable Objects
  SESSIONS: DurableObjectNamespace;

  // Containers (Sandboxes)
  claude_sandbox: Container;

  // Secrets (set via wrangler secret put)
  CLAUDE_API_KEY?: string;
  CLAUDE_CLIENT_ID?: string;
  CLAUDE_CLIENT_SECRET?: string;
  JWT_SECRET: string;

  // Environment variables
  ENVIRONMENT: string;
}

// Container types for Cloudflare Sandboxes
interface Container {
  get(id: string): ContainerInstance;
  newUniqueId(): DurableObjectId;
}

interface ContainerInstance {
  fetch(request: Request): Promise<Response>;
}
