// Generated by wrangler types command
// Run: npm run cf-typegen

import type { Sandbox } from '@cloudflare/sandbox';

declare global {
  interface Env {
    // KV Namespaces
    AUTH_KV: KVNamespace;
    SESSIONS_KV: KVNamespace;

    // R2 Buckets
    FILES_BUCKET: R2Bucket;

    // Durable Objects
    SESSIONS: DurableObjectNamespace;
    CHAT_SESSIONS: DurableObjectNamespace;

    // Containers (Sandboxes) - typed for @cloudflare/sandbox SDK
    SANDBOX_CONTAINER: DurableObjectNamespace<Sandbox>;

    // Secrets (set via wrangler secret put)
    JWT_SECRET: string;

    // Stripe billing (secrets via wrangler secret put)
    STRIPE_SECRET_KEY: string;
    STRIPE_WEBHOOK_SECRET: string;

    // Stripe public config (safe to commit)
    STRIPE_PRO_PRICE_ID: string;

    // 1Password service account — gives sandbox access to App Dev vault
    OP_SERVICE_ACCOUNT_TOKEN?: string;

    // Legacy project secrets (kept as fallback, prefer 1Password SDK)
    TURSO_DATABASE_URL?: string;
    TURSO_AUTH_TOKEN?: string;
    GITHUB_TOKEN?: string;
    ENCRYPTION_SECRET?: string;
    AUTH_SECRET?: string;
    SUPABASE_URL?: string;
    SUPABASE_SERVICE_ROLE_KEY?: string;

    // Static Assets binding (for run_worker_first mode)
    ASSETS: Fetcher;

    // Environment variables
    ENVIRONMENT: string;
  }
}

export {};
