/**
 * Agency Inspector — scripts injected into Astro preview iframe.
 *
 * getInspectorScript()  → browser JS that runs inside the iframe
 * getInjectionScript()  → Node script executed in the container to
 *                         tag .astro files and inject the <script> tag
 */

// ---------- Browser-side inspector ----------

const INSPECTOR_LINES: string[] = [
  '(function(){',
  '"use strict";',
  'if(window.parent===window)return;',
  'var P=window.parent;',
  'var selected=null;var hoverEl=null;',
  '',
  '// Shadow DOM custom elements — prevents user CSS from overriding overlay styles',
  'if(!customElements.get("vf-highlight")){',
  '  customElements.define("vf-highlight",class extends HTMLElement{',
  '    static get observedAttributes(){return["state"];}',
  '    connectedCallback(){this._sr=this.attachShadow({mode:"open"});this._upd();}',
  '    attributeChangedCallback(){if(this._sr)this._upd();}',
  '    _upd(){',
  '      var s=this.getAttribute("state")||"hover";',
  '      var b=s==="selected"?"2px solid rgba(168,85,247,.8)":"1px solid rgba(29,211,230,.5)";',
  '      var bg=s==="selected"?"rgba(168,85,247,.05)":"rgba(29,211,230,.03)";',
  '      var d=document.createElement("div");',
  '      d.style.cssText="all:initial;display:block;position:absolute;inset:0;border:"+b+";border-radius:3px;background:"+bg+";box-sizing:border-box;transition:border-color .12s ease,background .12s ease;";',
  '      while(this._sr.firstChild)this._sr.removeChild(this._sr.firstChild);',
  '      this._sr.appendChild(d);',
  '    }',
  '  });',
  '}',
  '',
  'if(!customElements.get("vf-tooltip")){',
  '  customElements.define("vf-tooltip",class extends HTMLElement{',
  '    static get observedAttributes(){return["label"];}',
  '    connectedCallback(){this._sr=this.attachShadow({mode:"open"});this._upd();}',
  '    attributeChangedCallback(){if(this._sr)this._upd();}',
  '    _upd(){',
  '      var t=this.getAttribute("label")||"";',
  '      var d=document.createElement("div");',
  '      d.style.cssText="all:initial;display:inline-block;background:rgba(168,85,247,.9);color:#fff;font:11px/1.2 system-ui,sans-serif;padding:2px 6px;border-radius:3px;white-space:nowrap;";',
  '      d.textContent=t;',
  '      while(this._sr.firstChild)this._sr.removeChild(this._sr.firstChild);',
  '      this._sr.appendChild(d);',
  '    }',
  '  });',
  '}',
  '',
  'function mkOv(state){',
  '  var d=document.createElement("vf-highlight");',
  '  d.setAttribute("state",state);',
  '  d.style.cssText="position:fixed;pointer-events:none;z-index:99999;display:none";',
  '  document.body.appendChild(d);return d;',
  '}',
  '',
  'function place(ov,el){',
  '  if(!el){ov.style.display="none";return;}',
  '  var r=el.getBoundingClientRect();',
  '  ov.style.top=r.top+"px";ov.style.left=r.left+"px";',
  '  ov.style.width=r.width+"px";ov.style.height=r.height+"px";',
  '  ov.style.display="block";',
  '}',
  '',
  'function closest(el){',
  '  var c=el;',
  '  var fallback=null;',
  '  while(c&&c!==document.body){',
  '    if(c.dataset&&c.dataset.vfComponent){',
  '      var info={component:c.dataset.vfComponent,',
  '                file:c.dataset.vfFile||"",',
  '                element:el,componentRoot:c};',
  '      // Prefer elements with a known file path; keep walking for better match',
  '      if(c.dataset.vfFile)return info;',
  '      if(!fallback)fallback=info;',
  '    }',
  '    c=c.parentElement;',
  '  }',
  '  return fallback;',
  '}',
  '',
  '// Fallback: auto-tag semantic elements when no vf-component found',
  'function autoTag(){',
  '  var sels=["header","nav","main","section","article","aside","footer"];',
  '  sels.forEach(function(tag){',
  '    document.querySelectorAll(tag).forEach(function(el,i){',
  '      if(el.dataset.vfComponent)return;',
  '      if(el.closest("[data-vf-component]"))return;',
  '      var id=el.id||(el.className?',
  '        String(el.className).split(/\\s+/)[0]:tag+"-"+i);',
  '      el.dataset.vfComponent=id;',
  '    });',
  '  });',
  '}',
  '',
  '// Tag semantic child elements within each top-level vf-component,',
  '// inheriting the parent file path so code editors load the right file.',
  'function tagChildren(){',
  '  var sels=["section","header","nav","aside","footer"];',
  '  document.querySelectorAll("[data-vf-component]:not([data-vf-parent])").forEach(function(par){',
  '    sels.forEach(function(tag){',
  '      par.querySelectorAll(tag).forEach(function(el,i){',
  '        if(el.dataset.vfComponent)return;',
  '        var id=el.id||',
  '          (el.className?String(el.className).split(/\\s+/)[0]:"")||',
  '          tag+"-"+i;',
  '        el.dataset.vfComponent=id;',
  '        el.dataset.vfFile=par.dataset.vfFile||"";',
  '        el.dataset.vfParent=par.dataset.vfComponent||"";',
  '      });',
  '    });',
  '  });',
  '}',
  '',
  'function discover(){',
  '  var tagged=document.querySelectorAll("[data-vf-component]");',
  '  if(tagged.length===0){autoTag();}else{tagChildren();}',
  '  tagged=document.querySelectorAll("[data-vf-component]");',
  '  var comps=[];var seen={};',
  '  tagged.forEach(function(el){',
  '    var n=el.dataset.vfComponent;',
  '    var f=el.dataset.vfFile||"";',
  '    var p=el.dataset.vfParent||"";',
  '    var k=n+":"+f;',
  '    if(!seen[k]){seen[k]=1;comps.push({component:n,file:f,parent:p});}',
  '  });',
  '  P.postMessage({type:"vf-tree",components:comps},"*");',
  '}',
  '',
  'function mkLabel(){',
  '  var d=document.createElement("vf-tooltip");',
  '  d.style.cssText="position:fixed;z-index:100000;pointer-events:none;display:none";',
  '  document.body.appendChild(d);return d;',
  '}',
  '',
  'function init(){',
  '  var selBox=mkOv("selected");',
  '  var hovBox=mkOv("hover");',
  '  var label=mkLabel();',
  '',
  '  document.addEventListener("mousemove",function(e){',
  '    var comp=closest(e.target);',
  '    if(comp&&comp.element!==selected){',
  '      place(hovBox,comp.element);',
  '      var r=comp.element.getBoundingClientRect();',
  '      var tag=comp.element.tagName.toLowerCase();',
  '      var txt=(comp.element.textContent||"").trim().slice(0,30);',
  '      label.setAttribute("label",txt?tag+" \\""+txt+"\\" in "+comp.component:tag+" in "+comp.component);',
  '      label.style.top=Math.max(0,r.top-20)+"px";',
  '      label.style.left=r.left+"px";',
  '      label.style.display="block";',
  '      hoverEl=comp.element;',
  '    }else{',
  '      hovBox.style.display="none";',
  '      label.style.display="none";',
  '      hoverEl=null;',
  '    }',
  '  });',
  '',
  '  document.addEventListener("click",function(e){',
  '    // Block external links',
  '    var link=e.target.closest("a[href]");',
  '    if(link){',
  '      var href=link.getAttribute("href");',
  '      if(href&&/^https?:\\/\\//.test(href)){',
  '        try{var u=new URL(href);',
  '          if(u.origin!==location.origin){',
  '            e.preventDefault();e.stopPropagation();return;',
  '          }',
  '        }catch(ex){}',
  '      }',
  '    }',
  '    var comp=closest(e.target);',
  '    if(comp){',
  '      e.preventDefault();e.stopPropagation();',
  '      selected=comp.element;',
  '      place(selBox,comp.element);',
  '      hovBox.style.display="none";label.style.display="none";',
  '      var elTag=comp.element.tagName.toLowerCase();',
  '      var elHTML=(comp.element.outerHTML||"").slice(0,1000);',
  '      var elText=(comp.element.textContent||"").trim().slice(0,100);',
  '      P.postMessage({type:"vf-select",',
  '        component:comp.component,',
  '        file:comp.file,',
  '        elementTag:elTag,',
  '        elementHTML:elHTML,',
  '        elementText:elText',
  '      },"*");',
  '    }else{',
  '      selected=null;selBox.style.display="none";',
  '      P.postMessage({type:"vf-deselect"},"*");',
  '    }',
  '  },true);',
  '',
  '  function updateOv(){',
  '    if(selected)place(selBox,selected);',
  '    if(hoverEl)place(hovBox,hoverEl);',
  '  }',
  '  window.addEventListener("scroll",updateOv,true);',
  '  window.addEventListener("resize",updateOv);',
  '',
  '  // Debounced discover to avoid spamming postMessage',
  '  var discoverTimer=null;',
  '  function debouncedDiscover(){',
  '    clearTimeout(discoverTimer);',
  '    discoverTimer=setTimeout(discover,200);',
  '  }',
  '',
  '  // Signal to parent that inspector is loaded and listening',
  '  P.postMessage({type:"vf-ready",url:location.href},"*");',
  '',
  '  discover();',
  '  new MutationObserver(function(){debouncedDiscover();})',
  '    .observe(document.body,{childList:true,subtree:true});',
  '',
  '  // Astro view-transitions support',
  '  document.addEventListener("astro:page-load",function(){',
  '    selected=null;selBox.style.display="none";discover();',
  '  });',
  '',
  '  window.addEventListener("message",function(e){',
  '    if(!e.data)return;',
  '    if(e.data.type==="vf-reload"){location.reload();return;}',
  '    if(e.data.type==="vf-deselect"){',
  '      selected=null;selBox.style.display="none";',
  '    }',
  '  });',
  '}',
  '',
  'if(document.readyState==="loading"){',
  '  document.addEventListener("DOMContentLoaded",init);',
  '}else{init();}',
  '})();',
];

export function getInspectorScript(): string {
  return INSPECTOR_LINES.join('\n');
}

// ---------- Container-side injection script ----------

const INJECTION_LINES: string[] = [
  'const fs=require("fs");',
  'const path=require("path");',
  'const W="/workspace";',
  '',
  'function walk(dir){',
  '  const out=[];',
  '  try{',
  '    const ents=fs.readdirSync(dir,{withFileTypes:true});',
  '    for(const e of ents){',
  '      if(e.name==="node_modules"||e.name===".git")continue;',
  '      const fp=path.join(dir,e.name);',
  '      if(e.isDirectory())out.push(...walk(fp));',
  '      else if(e.name.endsWith(".astro"))out.push(fp);',
  '    }',
  '  }catch{}',
  '  return out;',
  '}',
  '',
  'const files=walk(path.join(W,"src"));',
  'let tagged=0,heads=0;',
  '',
  'for(const file of files){',
  '  let c=fs.readFileSync(file,"utf8");',
  '  const rel=path.relative(W,file);',
  '  const name=path.basename(file,".astro");',
  '  let mod=false;',
  '',
  '  // Inject <script is:inline> before </head> (is:inline prevents Astro/Vite bundling)',
  '  if(c.includes("</head>")&&!c.includes("vf-inspector.js")){',
  '    c=c.replace("</head>",',
  '      \'<script is:inline src="/vf-inspector.js"><\\/script>\\n</head>\');',
  '    mod=true;heads++;',
  '  }',
  '',
  '  // Tag root element with data-vf-component (skip layouts)',
  '  if(!c.includes("data-vf-component")){',
  '    // Find HTML after frontmatter (--- ... ---)',
  '    const fm=c.match(/^---[\\s\\S]*?---/);',
  '    const start=fm?fm.index+fm[0].length:0;',
  '    const html=c.slice(start);',
  '    const m=html.match(/<([a-z][a-z0-9]*)\\b/i);',
  '    // Skip files whose root is <html> (layout files)',
  '    if(m&&m[1].toLowerCase()!=="html"){',
  '      const pos=start+m.index+m[0].length;',
  '      const attrs=\' data-vf-component="\'+name',
  '        +\'" data-vf-file="\'+rel+\'"\';',
  '      c=c.slice(0,pos)+attrs+c.slice(pos);',
  '      mod=true;tagged++;',
  '    }',
  '  }',
  '',
  '  if(mod)fs.writeFileSync(file,c);',
  '}',
  '',
  'console.log("vf-inject: "+files.length+" files scanned, "',
  '  +tagged+" tagged, "+heads+" <head> injected");',
];

export function getInjectionScript(): string {
  return INJECTION_LINES.join('\n');
}
