// Single source of truth for app version and changelog
// Update this file when releasing new versions

export const APP_VERSION = '0.29.0';

export interface ChangelogEntry {
  readonly version: string;
  readonly date: string;
  readonly tag: 'feature' | 'fix' | 'security' | 'breaking';
  readonly title: string;
  readonly items: readonly string[];
}

// Dev changelog — updated on EVERY commit, always growing
// Feature CHANGELOG (below) only updates when complete features ship
export interface DevLogEntry {
  readonly date: string;
  readonly summary: string;
}

export const DEV_CHANGELOG: readonly DevLogEntry[] = [
  { date: '2026-02-22', summary: 'Install prompt-kit code-block.tsx (CodeBlock+CodeBlockCode+CodeBlockGroup, shiki github-dark); replace ai-elements code-block in ChatPreview with CodeBlockWithCopy (header: language badge + filename + inline copy button); tool.tsx border border-border→border-teal-500/40' },
  { date: '2026-02-22', summary: 'source.tsx SourceContent HoverCard: add grid background pattern (border-purple-500/40, before: grid lines + radial mask) matching ContextContent and HelpButton popover aesthetic' },
  { date: '2026-02-22', summary: 'Install prompt-kit steps.tsx; add Steps+Sources and Steps+TextShimmer to ChatPreview; fix pill y-animation (min-w-[200px] stabilizes container so FLIP only moves y, revert layout="size" to layout); add animation-perf-check PreToolUse hook to settings.json' },
  { date: '2026-02-22', summary: 'Install prompt-kit tool.tsx (collapsible tool-call card: input-streaming/input-available/output-available/output-error states); fix pill x-wobble via layout="size" (animates width only, not position)' },
  { date: '2026-02-22', summary: 'Motion perf: TooltipButton transition-all → transition-[colors] (scoped to paint only); controls AnimatePresence mode=popLayout so siblings animate up immediately on exit instead of waiting for fade' },
  { date: '2026-02-22', summary: 'SessionIsland always visible; Session toggle now only shows/hides the button row (controlsOpen prop), pill stays on screen at all times' },
  { date: '2026-02-22', summary: 'HelpButton popover: purple border (border-purple-500/40), wider (w-72), architecture blurb header explaining real Linux container model, sharper per-control copy' },
  { date: '2026-02-22', summary: 'ChatPreview: add prompt-kit Source HoverCard chips (inline citations with favicon) + PulseLoader streaming bubble (status-reactive); pass status prop from PlaygroundPage; install chat-container + scroll-button prompt-kit components' },
  { date: '2026-02-22', summary: 'prompt-kit batch install: loader (all 12 variants + keyframes in tailwind.config.js), source (HoverCard-based with favicon), PulseLoader replaces motion.div in SessionIsland StreamingContent' },
  { date: '2026-02-22', summary: 'SessionIsland transition: LayoutGroup + motion.div layout on siblings so headline/prompt/suggestions glide on reveal; island entrance y+opacity only (removed scale+blur — compositor-only per fixing-motion-performance skill); tighter spring stiffness 500/damping 42/mass 0.5' },
  { date: '2026-02-22', summary: 'SessionIsland: hide by default, shown/hidden by Session toggle button (AnimatePresence scale+fade+y spring)' },
  { date: '2026-02-22', summary: 'SessionIsland: add HelpCircle button next to button row — click toggles a spring-animated popover listing each control (icon + label + description)' },
  { date: '2026-02-22', summary: 'SessionIsland: Dynamic Island-style session lifecycle control (idle/streaming/paused pill + Zap/Pause/Play/Stop button row with motion tooltips + vapor purple colors); installed smoothui dynamic-island; wired into PlaygroundPage between headline and prompt input' },
  { date: '2026-02-22', summary: 'Tune GlowEffect on submit button: scale 1.15→1.3 (pulse mode, was too subtle)' },
  { date: '2026-02-22', summary: 'Fix shimmer layout: submit button pinned right via flex-1 spacer; shimmer purple (#7c3aed→#d946ef); TextShimmer style merge fix (spread ...style after defaults so backgroundImage override works)' },
  { date: '2026-02-22', summary: 'TextShimmer prompt-kit component: shimmer keyframe in tailwind.config.js, "Claude is thinking..." shimmer in playground during streaming; submit button rounded-full + pulse glow (scale 1.15) replacing colorShift (was too erratic)' },
  { date: '2026-02-22', summary: 'Fix GlowEffect visibility on submit button: scale 0.85→1.4 so glow extends beyond bg-primary button edges and renders as a visible vapor-purple halo' },
  { date: '2026-02-22', summary: 'Fix BorderTrail corner radius: replace rect(... round) offsetPath (inconsistent browser support) with ResizeObserver + path() using computed SVG rounded-rect string; clamps radius to half min-dimension so it never overflows' },
  { date: '2026-02-22', summary: 'Playground redesign (input-prompt-redesign branch): ai-elements compound components (code-block, context, conversation, image, message, reasoning, sources), motion-primitives BorderTrail on PromptInput during streaming (purple gradient, radius=24 matches rounded-3xl), ChatPreview mock conversation with code/image blocks, close/reopen panel toggle, ibelick-converter agent' },
  { date: '2026-02-22', summary: 'Stream reconnect hardening: (1) persist after replay — useSandbox.ts calls persistMessage() after replay recovery so message survives page reload; (2) 30s grace period on WS close in ws-agent-server.js — transient disconnects no longer abort in-flight agent work, new connections still kill lingering activeChild immediately' },
  { date: '2026-02-21', summary: 'Smart Context Phase 2: auto session summaries — session-summarizer.ts generates AI summary (Haiku/Gemini Flash if API key configured) or rule-based fallback; persist endpoint triggers every 10 messages, writes to /workspace/.vaporforge/session-summary.md via sandboxManager.writeFile(); gather-context.sh ### Previous Session block picks it up on next session start' },
  { date: '2026-02-21', summary: 'Smart Context Phase 1 extras: MAX_CHARS 2048→4096, package name/version/framework detection in Code Intelligence section, Proactive Health Checks (staged console.logs, large files >500KB, unpushed commits, new TODOs, cached test failures); synced Dockerfile heredoc' },
  { date: '2026-02-21', summary: 'Usage Alerts: connect triggering to session spend — checkUsageAlerts() in persist endpoint accumulates spend in SESSIONS_KV, deduplicates per-session fired set, updates triggeredAt/Count in AUTH_KV; persistMessage passes costUsd + returns triggeredAlerts; done handler shows toast.warning() per triggered alert' },
  { date: '2026-02-21', summary: 'Usage Alerts: full-stack threshold alert system — 4 CRUD endpoints (GET/POST/PATCH/DELETE /api/billing/alerts), AlertConfig KV store (billing-alerts:{userId}), UsageAlertsCard component (preset+custom threshold, in-app channel badges, active/paused toggle, trigger history, empty state, budget context hint), wired into BillingTab below plan section' },
  { date: '2026-02-21', summary: 'BillingSDK integration: UpdatePlanCard (Free vs Pro plan comparison, animated expand, Monthly/Yearly toggle) + InvoiceHistory (card+table, status badges, hosted invoice links) replacing hand-rolled billing UI; TrialExpiryCard installed for future use; stripe-logo SVG asset + assets.d.ts; utils.ts (clsx+twMerge); billingsdk-config.ts Plan/CurrentPlan interfaces; shadcn UI components: card, button, badge, label, radio-group, toggle, table' },
  { date: '2026-02-21', summary: 'BillingTab: invoice history — GET /api/billing/invoices (stripe.invoices.list, last 12), invoice table with date/amount/status badge/PDF+hosted links; Billing Portal button always visible for users with history; billingApi.invoices() added to api.ts' },
  { date: '2026-02-21', summary: 'Stripe go-live: VaporForge Pro product created (prod_U1GNi5MhRBSiWj), price_1T3Dr7H6aZ92e8Tx0GsEMHP0 ($20/mo), webhook registered (we_1T3DrXH6aZ92e8Txz7WuaxYc), STRIPE_SECRET_KEY + STRIPE_WEBHOOK_SECRET set as wrangler secrets, wrangler.jsonc STRIPE_PRO_PRICE_ID updated' },
  { date: '2026-02-21', summary: 'Stripe billing integration: /api/billing/status + /checkout + /portal + /webhook; KV subscription state (subscription:{userId}, customer:{stripeId}); BillingTab in Settings; billingApi in api.ts; Stripe 2026-01-28.clover (current_period_end on SubscriptionItem)' },
  { date: '2026-02-21', summary: 'HIG UX Audit phase 6: IssueCard mobile overflow — drag handle + copy + delete hidden sm:flex (freed 132px), gap-3→gap-2, px-4→px-3; MarketplaceCard compact overflow — star minWidth 44→unset (height-only target, px-2 padding), Install button → Plus icon in compact; SettingsPage X close → HIG plain style (p-3, no rounded-md/hover-bg box)' },
  { date: '2026-02-21', summary: 'HIG UX Audit phase 5: SettingsPage mobile tab bar wobble fix (h-11 relative + absolute bottom-0 h-0.5 indicator replaces -mb-px border-b-2); AIProvidersTab Claude model selector → grid grid-cols-3 ModelButton tiles matching Gemini teal-border style; IssueTracker mobile header hidden sm:flex on Copy MD/Export/Import so Close always visible; filter chips overflow-x-auto single-row + mobile-only search row below' },
  { date: '2026-02-21', summary: 'HIG UX Audit phase 4: ConfigFileTab Upload/Add buttons 36px→44px, Edit/Toggle p-1.5→p-2.5, Delete inline confirm (confirmingFilename); SessionTabBar avatar h-9→h-11 (44px); ChatPanel clear-chat button → inline confirm (confirmingClear, red hover, 44px cancel X); WelcomeScreen inline rename Save/Cancel p-1→h-11 w-11, hover Rename/Delete p-1.5→p-2.5' },
  { date: '2026-02-21', summary: 'HIG UX Audit phase 3: SettingsPage inMobileSubView prop — suppress duplicate header on iPad (isMobile false in mobile subview); McpTab header mobile — icon-only buttons <640px (hidden sm:inline text, px-2→sm:px-3, min-w-0 truncate on h3); AIProvidersTab Claude model selector → iOS segmented control (3 pills in muted bg, no icon/grid); MoreMenu QuickChat entry (Zap icon, useQuickChat.getState().openQuickChat)' },
  { date: '2026-02-21', summary: 'HIG UX Audit phase 2: stable 44px header rows — McpTab count badge + Paste Config/Add Server buttons (min-h-[44px] wrapper, height:36px buttons, py-0.5 badge); ConfigFileTab Upload/Add buttons same pattern (Agents/Commands/Rules tabs); AIProvidersTab ModelButton vertical tile layout (flex-col, min-h:60px) replacing cramped horizontal layout' },
  { date: '2026-02-21', summary: 'HIG UX Audit (hig-ux-audit branch): touch targets 44px (PromptInputSubmit, SessionTabBar, suggestion chips); useFocusTrap hook + applied to 6 overlays; live swipe animation (contentRef DOM transform); edge swipe back (H8); tablet M7 Settings/Marketplace as full-screen overlay sheets; M8 Cmd+1/2/3 keyboard shortcuts; dead MobileDrawer.tsx deleted' },
  { date: '2026-02-21', summary: 'Session Remote: floating panel above prompt input with 4 lifecycle buttons (New/Checkpoint/Restore/Wrap Up); checkpoints stored in SESSIONS_KV; SessionRemote component + checkpoints API (GET/POST/DELETE /api/checkpoints)' },
  { date: '2026-02-21', summary: 'Component preview: add per-card Generate/Regenerate button — calls AI to produce CSS-variable-free example (bg-gray-* instead of bg-muted/bg-background), shows spinner during generation; generatedExample state in ComponentCard; iframe now white (#f8fafc) bg by default' },
  { date: '2026-02-21', summary: 'Fix component preview: add *Demo wrapper components to Table/Tabs/Breadcrumb/Dialog/Tooltip/Sheet catalog entries so data-dependent components render; update buildPreviewHtml detection to prefer *Demo/*Preview/*Example names over last generic uppercase component' },
  { date: '2026-02-20', summary: 'Fix component preview: switch to light theme (#f8fafc bg, dark text) matching shadcn pattern; top-aligned horizontal centering (justify-center, no vertical flex); update all stubs to light-mode shadcn colors; add Alert/AlertTitle/AlertDescription stubs; light-mode error display' },
  { date: '2026-02-20', summary: 'Fix component preview: add typescript to Babel preset (was react-only, silently failed on TS syntax); suppress Tailwind CDN p1 JIT errors in sandboxed null-origin iframe with targeted window.addEventListener error handler' },
  { date: '2026-02-20', summary: 'Changelog init: rewrite CHANGELOG.md (clean 3-tier format), create changelog.json + update changelog-action.json; header teal deploy badge (v{version} · Xm ago) using BUILD_TIMESTAMP' },
  { date: '2026-02-20', summary: 'Changelog sync: add missing public CHANGELOG entries for v0.26.0–v0.29.0 (What\'s New panel was stuck on v0.25.0)' },
  { date: '2026-02-20', summary: 'Component registry: Generate with AI (Haiku structured output) + manual Add form; instructions/setupScript/agents fields on all entries; docs+agents badges on cards; Files/Instructions tab in App Install Guide' },
  { date: '2026-02-20', summary: 'Dev Playground: personal component registry — user components stored in KV, add/delete UI, "My Components" filter pill, App Components category with Issue Tracker install guide (multi-file with tab viewer)' },
  { date: '2026-02-20', summary: 'Chore: add 3 SDK roadmap items to Notion (promptSuggestion, supportsAdaptiveThinking, supportedEffortLevels); restructure MEMORY.md 514→149 lines into vaporforge-history.md + vaporforge-patterns.md topic files' },
  { date: '2026-02-20', summary: 'UX: Auto model button (4th pill, new default) — sends no model param, always uses server default; explicit S/H/O lock to specific model' },
  { date: '2026-02-20', summary: 'Upgrade: default model claude-sonnet-4-5→4-6 + enable 1M context beta (betas: context-1m-2025-08-07) in buildOptions(); MODEL_MAP sonnet entry updated in sdk.ts' },
  { date: '2026-02-20', summary: 'Fix: create_plan tool description now prescriptive (ALWAYS call, NEVER use text) — prevents Claude from describing plans in plain text; remove tacky purple left border from MessageBody chat bubbles' },
  { date: '2026-02-20', summary: 'Security: fix IDOR on all 15+ agency site endpoints (userId ownership check via getOwnedSite()); fix shell injection in /source + preflight (array form exec); fix absolute path bypass in /file read+write; fix unrestricted git clone path in sessions' },
  { date: '2026-02-20', summary: 'maxBudgetUsd: per-session USD spend ceiling — KV storage, API endpoint, SandboxConfig field, VF_MAX_BUDGET_USD env var, buildOptions() pass-through + budget error detection; Settings → Command Center number input; Dockerfile mirrored' },
  { date: '2026-02-20', summary: 'Fix: no-language code blocks (tree diagrams, file listings) now render as pre-formatted blocks instead of wrapping inline code — whitespace-pre preserves tree structure' },
  { date: '2026-02-20', summary: 'Fix ask_user_questions: tool description now prescriptive (ALWAYS call, NEVER use text), execute ack tells Claude to STOP and wait; new container image d16f5f5d' },
  { date: '2026-02-20', summary: 'Wire create_plan + ask_user_questions to main sessions: vfTools in buildOptions() + MessageContent.tsx intercepts by tool name → PlanCard / AskQuestionsBlock; Dockerfile rebuilt with new container image fb6bb5c5' },
  { date: '2026-02-20', summary: 'Compaction indicator: claude-agent.js forwards system compacting events → isCompacting state → CompactionBanner in ChatPanel; PlanCard ai-element + create_plan tool in QuickChat; version bump 0.28→0.29' },
  { date: '2026-02-20', summary: 'QuestionFlow: ask_user_questions tool + QuestionFlow component — AI can present structured forms (text, select, multiselect, confirm) in QuickChat; answers submitted as next user message; version bump 0.27→0.28' },
  { date: '2026-02-20', summary: 'Tool UI components: CitationCard for WebFetch results (favicon, title, snippet, always-visible); upgraded Confirmation to ApprovalCard with destructive detection (red theme for rm/delete/drop); Globe icon for WebFetch, Search for Grep in ToolCallBlock' },
  { date: '2026-02-20', summary: 'Fix CLAUDE.md sync bug: syncConfigFromContainer now strips injected credential section before saving to KV; GET /user/claude-md returns empty instead of corrupt credential content' },
  { date: '2026-02-20', summary: 'Stream reconnect: WS drops mid-response now auto-recover via /api/sdk/replay — container buffers JSONL chunks per msgId, frontend replays missed frames on unexpected close' },
  { date: '2026-02-20', summary: 'ChatPanel: prompt input box always shows cyan glow by default; transitions to purple shadow when typing' },
  { date: '2026-02-20', summary: 'ChatPanel: centered welcome state with headline + suggestion chips when no messages; input pops to bottom once chat starts' },
  { date: '2026-02-19', summary: 'UI elements: fix Claude icon ring/size in MessageAvatar; add AgentStatusBadge to StreamingIndicator; SchemaViewer for tool input; HandoffChain in MessageContent; TokenCounter in PromptInputTools' },
  { date: '2026-02-19', summary: 'Replace Claude + Gemini icons with official SVGs; save mobile-ios-design + prompt-lookup skills to claude-codex' },
  { date: '2026-02-19', summary: 'vapor-sync: CLAUDE.md version 0.26.0→0.27.0 + Shadow DOM agency gotcha; MEMORY.md version fix; landing Features.astro adds Agency Mode card + layout SVG icon; FAQ.astro removes beta-phase language from billing question' },
  { date: '2026-02-19', summary: 'Model selector + provider icons: S/H/O pills in ChatPanel toolbar, Claude orange icon on assistant messages, Gemini star icon + blue border on gemini_* tool calls; VF_MODEL env var threads model choice through WS handler to claude-agent.js' },
  { date: '2026-02-19', summary: 'Agency inspector: fix Shadow DOM regression — use static getter syntax for observedAttributes (ES6 compatible vs ES2022 class fields); consolidate cssText multi-line concat to single string' },
  { date: '2026-02-19', summary: 'Agency inspector: Shadow DOM for overlays — vf-highlight + vf-tooltip custom elements with all:initial prevent user Astro CSS from overriding inspector styles' },
  { date: '2026-02-19', summary: 'Agency: fix closest() to prefer file-tagged ancestors (enables code editors to load on click); fire-and-forget inspector refresh on existing containers; useEffect tracks component name change; onSelect directly calls loadFilesForComponent in code mode' },
  { date: '2026-02-19', summary: 'Agency: preview refresh button (RotateCw); Debug panel global paste listener (Ctrl+V anywhere); description textarea for pasting HTML/CSS/errors; Analyze works with image OR text' },
  { date: '2026-02-19', summary: 'Agency Code Mode: 3 bug fixes — CSS placeholder for Tailwind-only components; codeModeRef filters vf-select with empty file; inspector tagChildren() discovers semantic sections within Astro components; ComponentTree renders children indented under parent' },
  { date: '2026-02-19', summary: 'Agency Code Mode: fix iframe not updating after save — scheduleIframeReload (debounced src reset) fires after every debounced save + Inline AI apply; CSS editor now shows embedded <style> block instead of global.css; patchStyleBlock writes CSS edits back into .astro file' },
  { date: '2026-02-19', summary: 'Bump version to 0.27.0: Agency Code Mode — dual Monaco editors + Inline AI in visual Astro editor' },
  { date: '2026-02-19', summary: 'Agency Code Mode (Task 7): wire helpers + code editors into AgencyEditor — loadFilesForComponent, saveFile (1s debounce), handleAstroChange/CssChange, handleInlineAIInsert; PanelGroup vertical split preview+editors; AgencyInlineAI in right panel' },
  { date: '2026-02-19', summary: 'Agency Code Mode: create AgencyCodePane (dual Monaco editors, horizontal PanelGroup) and AgencyInlineAI (SSE stream generate, apply button) components; add GET/PUT file + POST inline-ai backend endpoints' },
  { date: '2026-02-19', summary: 'Agency: add debug panel — paste/drop screenshot, stream AI vision analysis for CSS specificity issues; debug endpoint uses AI SDK streamText with Claude/Gemini API key' },
  { date: '2026-02-19', summary: 'Agency: update fullPrompt CSS specificity rules — agent now checks for explicit CSS class color declarations before adding Tailwind utilities, uses ! prefix for overrides; reads CSS files when instruction involves colors' },
  { date: '2026-02-19', summary: 'Agency: fix post-edit preview reload — switch from contentWindow.postMessage (silently dropped if inspector not listening) to iframe.src=iframe.src (always works); bump delay 3s→5s for Astro rebuild time' },
  { date: '2026-02-19', summary: 'Agency: fix root cause of WebSocket connection failure — index.ts WS interceptor only routed /api/sdk/ws through Hono; /api/agency/edit-ws fell to DO branch and returned 400 Missing sessionId since agency WS uses siteId not sessionId' },
  { date: '2026-02-19', summary: 'Agency: WS debug — remove startWsServer from WS handler (pre-flight handles it), add console.log for wsConnect status to diagnose silent failures' },
  { date: '2026-02-19', summary: 'Agency: move all edit prep (token type check, WS warm-up, prompt build, context file write) to pre-flight; WS handler is now trivial proxy; fixes silent 401 when user has API key instead of OAuth token' },
  { date: '2026-02-19', summary: 'Agency: add HTTP pre-flight before WS connect — calls /api/agency/edit-preflight to warm WS server and get readable JSON error; OAuth token check improved with better error messages' },
  { date: '2026-02-19', summary: 'Agency: fix streaming panel UX — show working indicator whenever isStreaming (not just when output exists); persist output after stream ends; clear output at start of next edit only; add WS error message on onerror' },
  { date: '2026-02-19', summary: 'Agency: surface agent errors in streaming panel — handle error+stderr WS message types (were silently dropped); forward [claude-agent] stderr to client for visibility' },
  { date: '2026-02-19', summary: 'Agency: GitHub repo browser in New Site modal — browse/filter repos by username, Astro-only toggle, 1hr cache, auto-fills name+url on select' },
  { date: '2026-02-18', summary: 'Agency: fix no-changes bug — disable continue:true in agency mode (fresh session per edit), fix adjacent→selected instruction, add VF_AUTO_CONTEXT:0, add git status to diff endpoint' },
  { date: '2026-02-18', summary: 'Agency: ready handshake (vf-ready postMessage), connection indicator dot, live streaming output in EditPanel, vf-reload postMessage instead of src reset' },
  { date: '2026-02-18', summary: 'Agency: fix WS edit-ws connection failure — replace 300ms fixed wait with port-bound poll (up to 10s); pre-start ws-agent-server when session becomes ready' },
  { date: '2026-02-18', summary: 'Fix v0.26.0: remove Astro MCP injection (was blocking SDK query); add 3s delay before iframe reload for Astro rebuild; fix APP_VERSION to 0.26.0' },
  { date: '2026-02-18', summary: 'Bump version to 0.26.0: Agency Editor v2 release (child element inspector, enriched AI context, iframe auto-reload, Astro docs MCP)' },
  { date: '2026-02-18', summary: 'Agency: inject Astro docs MCP (https://mcp.docs.astro.build/mcp) into every agency edit session via CLAUDE_MCP_SERVERS env var' },
  { date: '2026-02-18', summary: 'Agency: enrich AI prompt with elementHTML (selected element outerHTML) and full file source (6000 char cap) for precise edits' },
  { date: '2026-02-18', summary: 'Agency: GET /sites/:id/source reads Astro file from container via execInSandbox cat, 6000 char cap' },
  { date: '2026-02-18', summary: 'Agency: pass elementHTML as WS query param in handleSendEdit; force iframe reload after edit completes' },
  { date: '2026-02-18', summary: 'EditPanel header shows element tag and text snippet (e.g. "button \\"Get Started\\" in HeroCentered.astro")' },
  { date: '2026-02-18', summary: 'Agency types: add elementTag/elementHTML/elementText to ComponentInfo, SelectedComponent, and onSendEdit signature' },
  { date: '2026-02-18', summary: 'Agency inspector: handle vf-reload postMessage to trigger location.reload() in iframe' },
  { date: '2026-02-18', summary: 'Agency inspector: vf-select postMessage now includes elementTag, elementHTML (1000 char cap), elementText (100 char cap) for AI context' },
  { date: '2026-02-18', summary: 'Fix agency inspector: closest() now returns specific hovered/clicked element instead of component root; label shows tag+text context' },
  { date: '2026-02-18', summary: 'Fix agency edits: embed file path + rules in prompt (VF_SYSTEM_PROMPT not read by claude-agent.js); re-enable Astro Dev Toolbar' },
  { date: '2026-02-18', summary: 'Fix Agency Mode edits: add WS endpoint /api/agency/edit-ws, remove 18s delay, agent now properly invoked via WS tunnel' },
  { date: '2026-02-18', summary: 'Fix Agency Mode: patch astro.config.mjs to disable devToolbar+HMR (env var unreliable), delay commit/reload 18s for agent to finish' },
  { date: '2026-02-18', summary: 'Fix agency setup: skip clone if workspace exists, skip install if node_modules present, astro binary fallback to npx, add /edit/logs endpoint' },
  { date: '2026-02-18', summary: 'Fix agency dev server: liveness check after isPortExposed, restart without re-clone, use astro binary directly instead of npm run dev' },
  { date: '2026-02-18', summary: 'Fix agency inspector: add is:inline to script tag, disable Astro Dev Toolbar, scale up loading screen for HIG accessibility' },
  { date: '2026-02-18', summary: 'CLAUDE.md audit: remove 120 lines of global duplicates, add Agency Mode docs, update version to 0.25.0' },
  { date: '2026-02-18', summary: 'Add agency inspector: click-to-select components, hover highlights, component tree discovery, auto-tagging of .astro files' },
  { date: '2026-02-18', summary: 'Fix agency dev server binding: pass --host 0.0.0.0 so container is reachable on 10.0.0.1' },
  { date: '2026-02-18', summary: 'Fix agency preview URL hostname extraction (was stripping to just "dev")' },
  { date: '2026-02-18', summary: 'Add two-changelog system: DEV_CHANGELOG (every commit) + CHANGELOG (feature releases)' },
  { date: '2026-02-18', summary: 'Add brand logos to AboutTab, WelcomeScreen, AgencyLoadingScreen, Hero, TechStack' },
  { date: '2026-02-20', summary: 'Add autonomy selector (Conservative/Standard/Autonomous) — maps to SDK permissionMode, threaded through WS stack' },
  { date: '2026-02-20', summary: 'Add cost meter — captures token usage from SDK result event, shown as input/output counts below assistant messages' },
  { date: '2026-02-20', summary: 'Fix cost meter pipeline: capture total_cost_usd from SDK result, pass through done frame, fix api.ts usage passthrough bug, show cost per-message and session total' },
];

export const CHANGELOG: readonly ChangelogEntry[] = [
  {
    version: '0.29.0',
    date: '2026-02-20',
    tag: 'feature',
    title: 'Model Control, Cost Tracking, and Budget Limits',
    items: [
      'Model selector: choose Sonnet (S), Haiku (H), Opus (O), or Auto (default) per message',
      'Autonomy selector: Conservative, Standard, or Autonomous permission mode per session',
      'Cost meter: see input/output token counts and estimated USD cost per message and session total',
      'Budget control: set a per-session USD spend ceiling in Command Center',
      'Compaction indicator: banner appears when Claude is compacting context mid-session',
      'Structured plan creation: Claude uses create_plan tool to present plans as interactive cards',
      'Upgrade to Claude Sonnet 4.6 with 1M token context window beta enabled',
    ],
  },
  {
    version: '0.28.0',
    date: '2026-02-20',
    tag: 'feature',
    title: 'Structured AI Forms + Stream Reconnect',
    items: [
      'QuestionFlow: Claude can ask structured questions (text, select, multiselect, confirm) in Quick Chat',
      'Stream reconnect: if your connection drops mid-response, the stream auto-resumes from where it left off',
      'Citation cards for web search results: favicon, title, snippet, and source URL always visible',
      'Approval cards detect destructive operations (rm, delete, drop) and display a red warning theme',
      'Chat welcome state: suggestion chips appear on an empty chat to help you get started',
      'Chat input glows cyan by default and transitions to purple when you start typing',
    ],
  },
  {
    version: '0.27.0',
    date: '2026-02-19',
    tag: 'feature',
    title: 'Agency Code Mode — Edit Astro Sites Directly',
    items: [
      'Dual Monaco editors in Agency: edit component code and CSS side by side',
      'Inline AI: describe a change in plain English and apply it directly to the selected file',
      'Shadow DOM inspector overlays — highlight and tooltip elements no longer affected by site CSS',
      'GitHub repo browser in the New Site modal: search and filter your repos, Astro-only toggle',
      'Debug panel: paste or drop a screenshot and get AI analysis of CSS specificity issues',
      'Pre-flight check: readable error messages before WebSocket connection (was silent failure)',
    ],
  },
  {
    version: '0.26.0',
    date: '2026-02-18',
    tag: 'feature',
    title: 'Agency Editor v2 — Richer Context for AI Edits',
    items: [
      'Click-to-select now captures element tag, visible text, and full HTML for the AI',
      'AI reads the full Astro source file before making edits (6000 char cap)',
      'Edit panel header shows exactly which element you have selected',
      'iframe auto-reloads after every AI edit — see changes without manual refresh',
      'Astro docs injected as MCP context so the AI understands Astro-specific syntax',
    ],
  },
  {
    version: '0.25.0',
    date: '2026-02-17',
    tag: 'feature',
    title: 'Agency Mode — Visual Editor for Client Sites',
    items: [
      'Admin-only Agency dashboard with site management (add, edit, delete)',
      'Visual editor with live iframe preview and viewport presets (desktop, tablet, mobile)',
      'Click-to-select inspector overlay — click any component to target it for AI editing',
      'Component tree sidebar with category grouping',
      'AI edit pipeline with scoped system prompts and post-edit validation',
      'Auto-commit after every edit with descriptive messages',
      'Staging workflow — view git diff and push changes live',
      'Removed legacy vaporforge.jbcloud.app route (primary domain: vaporforge.dev)',
    ],
  },
  {
    version: '0.24.0',
    date: '2026-02-17',
    tag: 'fix',
    title: 'Streaming Reliability + Shimmer Fix',
    items: [
      'Hash-based skip logic — redundant MCP config writes and npm installs skipped when unchanged',
      'Fixed shimmer indicator — "Thinking..." now shows text with gradient sweep instead of solid rectangle',
      'WS server and npx packages pre-installed at session creation time',
      'File polling replaces hardcoded 150ms wait for context file in container',
      'Config + user secrets fetched concurrently (Phase 1 parallel KV reads)',
    ],
  },
  {
    version: '0.23.2',
    date: '2026-02-16',
    tag: 'fix',
    title: 'Mobile Home Screen Horizontal Shift Fix',
    items: [
      'Fixed cards overflowing viewport on mobile (explicit grid-cols-1 + min-w-0 containment)',
      'Replaced hover:scale with active:scale press states per Apple HIG (no more sticky hover on touch)',
      'All card containers properly constrained within viewport width — no band-aid overflow-hidden',
    ],
  },
  {
    version: '0.23.1',
    date: '2026-02-17',
    tag: 'fix',
    title: 'Apple HIG Polish — Touch Targets + Typography',
    items: [
      'All interactive elements now meet 44pt minimum touch target (was 36px in several places)',
      'Settings mobile tab strip: 44pt height with 13px Footnote text and 18px icons',
      'iPad sidebar: session buttons and New Session upgraded from 36px to 44pt',
      'MoreMenu: all menu items and session buttons now 44pt touch targets',
      'MobileNavBar title uses 15px Subheadline per iOS type scale',
      'All section labels upgraded from 10px to 11pt Caption 2 minimum',
      'Redundant Settings top bar hidden on mobile (MobileNavBar already shows title)',
    ],
  },
  {
    version: '0.23.0',
    date: '2026-02-16',
    tag: 'feature',
    title: 'Mobile Layout Redesign (Apple HIG)',
    items: [
      'Apple HIG mobile layout: iPhone bottom tab bar (49pt + safe area), iPad 280px sidebar',
      'MobileNavBar: 44pt translucent blur nav bar with back/title/actions',
      'MobileTabBar upgrade: 25pt SF Symbol-style icons, system colors, blur background',
      'Sub-navigation system: Settings and Marketplace render inline within mobile layouts',
      'TabletLayout: iPad sidebar with logo, session nav, tools, sessions list',
      'Swipe gesture navigation between tabs on iPhone',
      'Viewport fix: 100dvh when keyboard closed fills full dynamic viewport including behind address bar',
    ],
  },
  {
    version: '0.22.0',
    date: '2026-02-16',
    tag: 'feature',
    title: 'Smart Context Phase 1 — Session Auto-Context',
    items: [
      'gather-context.sh: fault-tolerant bash script gathers git status, TODOs, code metrics, previous session context',
      'Auto-context cached at container startup via ws-agent-server.js',
      'buildSystemPromptAppend() reads cached context and appends to system prompt',
      'Auto-context toggle in Command Center settings with optimistic UI update',
      '.vaporforge/knowledge/ directory created in container for Phase 2 prep',
    ],
  },
  {
    version: '0.21.2',
    date: '2026-02-16',
    tag: 'feature',
    title: 'MCP Credential Files + Reliability',
    items: [
      'Multi-file credential support: upload multiple credential files per MCP server',
      'Credential file paths auto-injected into container CLAUDE.md so the agent knows they exist',
      'Fresh MCP config on every message: no more stale config from session creation time',
      'npx package pre-install: stdio MCP servers using npx no longer fail silently in containers',
      'Diagnostic logging: transport-type logging shows exactly which MCP servers the agent receives',
      'Fixed stdio command field parsing: split command into executable + args correctly',
    ],
  },
  {
    version: '0.21.1',
    date: '2026-02-15',
    tag: 'feature',
    title: 'Credential File Upload for MCP Servers',
    items: [
      'Upload credential files (service account JSON, PEM keys, etc.) for stdio MCP servers',
      'Files stored per-server in KV, injected to container filesystem at configured paths',
      'Instructional UI guides users through the credential file workflow',
      'Credential paths automatically appended to sandbox CLAUDE.md',
    ],
  },
  {
    version: '0.21.0',
    date: '2026-02-15',
    tag: 'feature',
    title: 'MCP Server Management Upgrade',
    items: [
      'Paste JSON config to add servers (supports Claude Code, Warp, and raw formats)',
      'Custom HTTP headers for server authentication (Bearer tokens, API keys)',
      'Environment variables for stdio/CLI servers',
      'Tool discovery: ping servers to see available tools as pill badges',
      'Multi-server batch add from pasted JSON blocks',
    ],
  },
  {
    version: '0.20.0',
    date: '2026-02-15',
    tag: 'feature',
    title: 'WebSocket Streaming — Real-Time Chat',
    items: [
      'Main chat now streams text in real-time via WebSocket (was buffered 60s+ with SSE)',
      'WebSocket agent server in container: spawns claude-agent.js, pipes stdout as WS frames',
      'Worker proxies WS connection directly to sandbox port 8765 via sandbox.wsConnect()',
      'Context file pattern: Worker writes secrets to /tmp, container reads and deletes',
      'POST /persist endpoint: browser saves full response text after stream completes',
      'Bypasses Cloudflare Sandbox execStream() SSE/RPC buffering — the root cause of no streaming',
    ],
  },
  {
    version: '0.19.0',
    date: '2026-02-15',
    tag: 'fix',
    title: 'Fix Streaming + Visual Polish',
    items: [
      'Fixed main chat streaming: text now appears progressively instead of all at once after 60s',
      'Root cause: Node.js block-buffered stdout in piped containers — replaced with unbuffered fs.writeSync',
      'Smooth text rendering: typewriter buffer drips characters at controlled rate during streaming',
      'Adaptive speed: catches up faster when text arrives in bursts (>200 chars behind)',
      'Dockerfile script synced: plan mode, tool dedup, composite IDs, session retry now in container',
      'Prompt input polish: muted background, hover state, stronger focus glow, backdrop blur',
    ],
  },
  {
    version: '0.18.0',
    date: '2026-02-15',
    tag: 'feature',
    title: 'Compound PromptInput + Streaming Fix',
    items: [
      'AI Elements compound PromptInput: 12 composable sub-components replace 467-line monolith',
      'Drag-and-drop image upload scoped to input area with visual overlay',
      'Voice input via Web Speech API (Chrome) with pulsing mic indicator',
      'File attachment button for image selection',
      'Status-aware submit button: idle, streaming (stop), uploading (spinner)',
      'Streaming fix: stopStreaming now directly resets isStreaming state as safety net',
      'QuickChatPanel upgraded to compound PromptInput',
      'ChatPanel upgraded with composable tools toolbar, Reforge, and mode toggle',
    ],
  },
  {
    version: '0.17.0',
    date: '2026-02-15',
    tag: 'feature',
    title: 'Semantic Search — Find Code by Meaning',
    items: [
      'Semantic search: ask "where is auth logic?" and find files by concept, not just text',
      'Google text-embedding-004 indexes up to 500 workspace files automatically on session create',
      'semanticSearch tool in Quick Chat: AI proactively searches codebase for conceptual queries',
      'Source citations: file pills with relevance scores appear after semantic search results',
      'Click any source pill to open the file directly in the editor',
      'Embedding status badge in Quick Chat header: shows indexing progress and file count',
      'Re-index button to rebuild embeddings after file changes',
      'Requires Gemini API key — gracefully hidden when not configured',
    ],
  },
  {
    version: '0.16.0',
    date: '2026-02-15',
    tag: 'feature',
    title: 'Chat Visual Overhaul + DevTools',
    items: [
      'LaTeX math rendering: inline ($E=mc^2$) and block ($$) via KaTeX',
      'Streaming markdown hardening: unclosed code fences, bold, italic, and tables render correctly mid-stream',
      'Message avatars: Bot/User icons with streaming pulse animation on assistant avatar',
      'Relative timestamps on messages ("2m ago") with 30s auto-refresh',
      'Left border accent on assistant messages for visual hierarchy',
      'Stop streaming button: abort mid-stream and keep partial response',
      'Thumbs up/down feedback on messages (persisted to localStorage)',
      'Task Plan view: agent workflows with 3+ tool calls show a grouped phase timeline (Exploring, Implementing, Testing, Committing)',
      'DevTools Stream tab: real-time event log with type filter',
      'DevTools Tokens tab: per-message token estimates with input/output breakdown',
      'DevTools Latency tab: TTFT, stream duration, and tokens/sec gradient meters',
      'Code block shimmer skeleton during streaming (replaces blank block)',
    ],
  },
  {
    version: '0.15.1',
    date: '2026-02-15',
    tag: 'feature',
    title: 'Keyboard Shortcuts + Panel Persistence + Wiki',
    items: [
      'Settings now shows all 15 keyboard shortcuts across 5 groups (was 7)',
      'New AI Tools shortcut group: Quick Chat, Code Transform, Code Analysis, Commit Message',
      'Panel sizes persist across page reloads — resize once, keep your layout',
      'Cmd+Shift+0 resets panels to default (or your saved custom default)',
      'Panel Layout card in Settings: visual size preview with Save/Reset buttons',
      'Wiki tab in Dev Panel: documents what each VaporForge surface can do',
    ],
  },
  {
    version: '0.15.0',
    date: '2026-02-15',
    tag: 'feature',
    title: 'Tool-Calling Agent for Quick Chat',
    items: [
      'Quick Chat now acts as a mini-agent when a sandbox session is active',
      'AI can read files, list directories, search code, and run commands in your sandbox',
      'Run Command requires explicit approval before execution (human-in-the-loop)',
      'Tool invocations displayed as collapsible cards with state badges (running, done, error, denied)',
      'Agent mode indicator in Quick Chat header when sandbox tools are available',
      'Multi-step tool chains: AI can call up to 10 tools per message to complete complex tasks',
    ],
  },
  {
    version: '0.14.2',
    date: '2026-02-14',
    tag: 'feature',
    title: 'Quick Chat — AI SDK useChat Migration',
    items: [
      'QuickChatPanel rewritten with AI SDK v6 useChat hook and DefaultChatTransport',
      'Backend stream endpoint returns UIMessageStreamResponse for native useChat consumption',
      'Message format upgraded to UIMessage parts[] (text, reasoning) with backward-compatible parsing',
      'Local input state replaces useChat-managed input for direct control',
      'Removed legacy streamQuickChat SSE generator — all streaming now handled by AI SDK transport',
      'Fixed maxTokens → maxOutputTokens rename across quickchat and transform endpoints',
    ],
  },
  {
    version: '0.14.1',
    date: '2026-02-14',
    tag: 'feature',
    title: 'Chat Performance — Normalized State + Memoized Messages',
    items: [
      'Normalized message state: messages stored in Record<id, Message> + ordered ID array for O(1) lookup',
      'Granular Zustand selectors: streaming updates no longer re-render historical messages',
      'React.memo on MemoizedMessageItem: each message only re-renders when its own data changes',
      'Isolated StreamingMessage component: subscribes only to streaming state, decoupled from message list',
      'MessageContent wrapped in React.memo for nested render isolation',
      'useMessage(id) / useMessageIds() / useMessageCount() selector hooks for per-message subscriptions',
    ],
  },
  {
    version: '0.14.0',
    date: '2026-02-14',
    tag: 'feature',
    title: 'AI Elements Chat UX — Suggestion, Reasoning, Shimmer',
    items: [
      'Suggestion chips: reusable compound component (Suggestions + Suggestion) in main chat and Quick Chat empty states',
      'Reasoning upgrade: Radix Collapsible with auto-open on stream start, auto-close after stream end, duration timer ("Thought for Ns")',
      'Shimmer text effect: CSS gradient sweep animation on streaming status labels (Thinking, Reasoning, Writing)',
      'Collapsible animations: smooth height transitions via Radix CSS variables',
      'cn() utility: lightweight class name joiner for component styling',
      'AI Elements component library: new ui/src/components/ai-elements/ directory for adapted Vercel AI Elements',
    ],
  },
  {
    version: '0.13.1',
    date: '2026-02-14',
    tag: 'feature',
    title: 'Live Plugin Catalog + Custom Sources',
    items: [
      'Add Plugin from URL: paste any GitHub repo URL to discover and install plugins directly',
      'Custom Source Repos: add your own GitHub repos as browsable plugin sources (max 10)',
      'Dynamic source filters: sidebar shows custom sources with live plugin counts and remove buttons',
      'Custom source badge (green) on marketplace cards for user-added plugins',
      'Refresh Installed: re-fetch latest content from GitHub for all git-sourced plugins',
      'Right-side controls: close/exit buttons moved to right side of all headers for consistency',
    ],
  },
  {
    version: '0.13.0',
    date: '2026-02-15',
    tag: 'feature',
    title: 'Config Persistence — Never Lose Data Again',
    items: [
      'Auto-restore CLAUDE.md, plugins, MCP servers, and user configs after container recycle',
      'Sentinel stamp file detects missing config without expensive re-reads',
      'Sync-back: in-container CLAUDE.md edits persist to KV after each message',
      'Config Sync section in DevTools with stamp status and Force Re-sync button',
      'Toast notification when config is restored after container wake',
    ],
  },
  {
    version: '0.11.0',
    date: '2026-02-13',
    tag: 'feature',
    title: 'Structured Intelligence + Dev Changelog',
    items: [
      'Code Analysis panel: streamObject() with progressive complexity meter, severity-badged issues (Cmd+Shift+A)',
      'Smart Commit Message: generateObject() card with editable type/scope/subject/body and preview (Cmd+Shift+G)',
      'Test Results Parser: auto-detects Jest/Vitest/pytest/Mocha output with pass/fail/skip progress bar',
      'Stack Trace Parser: clickable frames, dimmed node_modules, opens file in editor',
      'Dev Changelog: full-page overlay with date-grouped commits, expandable details, search, and filter (Cmd+Shift+L)',
      'Build-time version script: git hash, date, and commit log generated at build time for edge runtime',
      'Version badge in SessionTabBar shows app version and build hash',
    ],
  },
  {
    version: '0.10.0',
    date: '2026-02-12',
    tag: 'feature',
    title: 'AI SDK Integration — Quick Chat + Code Transform',
    items: [
      'Quick Chat: instant AI chat without starting a sandbox (Cmd+Shift+Q)',
      'Multi-provider support: switch between Claude and Gemini models on the fly',
      'Code Transform: select code in editor, describe a change, get a diff view (Cmd+Shift+T)',
      'Provider availability guard: auto-selects configured provider, disables unavailable ones',
      'Chat history persisted in KV with 7-day TTL',
      'Dev Tools settings panel: build version tracking with client/server mismatch detection',
      'Fixed stale Gemini model IDs (preview models replaced with stable versions)',
    ],
  },
  {
    version: '0.9.6',
    date: '2026-02-12',
    tag: 'feature',
    title: 'Gemini AI Integration',
    items: [
      'Google Gemini available as an AI provider — Claude can delegate tasks to Gemini',
      'Three Gemini tools: quick_query (Flash), analyze_code (Pro), codebase_analysis (Pro+files)',
      'AI Providers settings tab: add API key, toggle provider, choose default model',
      'Gemini expert agent: use /agent:gemini-expert for full Gemini delegation mode',
      'Auto-retry with exponential backoff on rate limits (429) — handles free tier gracefully',
      'Zero-dependency MCP server runs inside the sandbox container',
      'Free tier: 1,000 requests/day with any personal Gmail account',
    ],
  },
  {
    version: '0.9.5',
    date: '2026-02-13',
    tag: 'feature',
    title: 'VaporFiles Manager + Copy MD Fix',
    items: [
      'VaporFiles tab in Settings: browse, upload, preview, and delete R2 files',
      'Image gallery with thumbnail grid and full-screen preview modal',
      'Drag-and-drop upload with visual drop zone indicator',
      'Copy shareable R2 URLs for any file (permanent, cached)',
      'Files persist across sessions — R2 storage is independent of sandboxes',
      'Copy MD now respects multi-select: copies all selected issues, not just current tab',
      'Header Copy MD button changes color and shows count when items selected',
      'Fixed file deletion bug: was passing ID without extension to R2',
    ],
  },
  {
    version: '0.9.4',
    date: '2026-02-09',
    tag: 'feature',
    title: 'Command Center + Plugin Refresh',
    items: [
      'Command Center settings tab: edit internal container rules for Claude SDK',
      'VF rules prepended to CLAUDE.md in every sandbox — Claude now knows its environment',
      'Default rules cover container awareness, MCP relay, secrets, and what NOT to do',
      'Reset to defaults button to restore original VF rules',
      'Plugin refresh endpoint: re-discover all git-sourced plugins from GitHub',
      'Refresh preserves user toggle states (enabled/disabled) while updating content',
      'Config injection order documented in Command Center UI',
    ],
  },
  {
    version: '0.9.3',
    date: '2026-02-09',
    tag: 'feature',
    title: 'Slash Commands + Plugin Pipeline Fix',
    items: [
      'Slash command autocomplete: type / in chat to see matching commands',
      'Rich built-in command templates for /review, /test, /docs, /refactor',
      'Plugin discover supports monorepo subpaths and root-level convention dirs',
      'Catalog toggle bug fixed: plugins no longer share URLs',
      'Marketplace install creates fallback commands from catalog metadata',
    ],
  },
  {
    version: '0.9.2',
    date: '2026-02-09',
    tag: 'feature',
    title: 'Warp-Style Layout Overhaul',
    items: [
      'Chat moved to center panel (55%), editor+terminal to right sidebar (30%)',
      'SessionTabBar: horizontal tabs with click, double-click rename, hover close',
      'Focus mode (Cmd+3): collapse both sidebars for full-screen chat',
      'Right panel auto-expands when file opened from file tree',
      'Delete All button for pending-delete sessions section',
    ],
  },
  {
    version: '0.9.1',
    date: '2026-02-09',
    tag: 'feature',
    title: 'Landing Page Visual Overhaul + 3-Tier Pricing',
    items: [
      '3-tier pricing: Free/$0, Pro/$20, Premium/$80 with feature highlights',
      'Compare table: VF Pro, VF Premium, Cursor, Codespaces, and Replit side-by-side',
      'Feature cards: bigger titles, gradient text, keyword pills, hover lift',
      'Premium tier numbers highlighted in cyan to show upgrade value',
      'Nav restyled: all links brighter, accent links in purple with separator',
      'FAQ brighter borders with hover glow, TechStack card-wrapped details',
    ],
  },
  {
    version: '0.9.0',
    date: '2026-02-09',
    tag: 'feature',
    title: 'Frontend MCP Relay',
    items: [
      'Connect local MCP servers to cloud SDK via WebSocket relay chain',
      'Relay proxy in container forwards JSON-RPC to local stdio servers',
      'Relay status indicator in header with connection state',
      'McpTab settings UI for adding/removing relay servers',
      'Session API extended with MCP relay config persistence',
    ],
  },
  {
    version: '0.8.0',
    date: '2026-02-09',
    tag: 'feature',
    title: 'MCP Persistence + Plugins System',
    items: [
      'MCP servers now persist — writes directly to ~/.claude.json in sandbox',
      'Plugins and Agents settings tab with visual agent-command connections',
      'iPad safe area fix, GitHub repo browser, and favorites list',
      'Add/remove buttons visible and usable on touch devices',
      'Favicon updated to match landing page logo',
    ],
  },
  {
    version: '0.7.1',
    date: '2026-02-08',
    tag: 'fix',
    title: 'Chat Persistence Fix',
    items: [
      'SDK stream endpoint now writes messages to KV for persistence',
      'User messages saved before stream, assistant messages saved after',
      'Chat history survives page refresh and session reconnect',
    ],
  },
  {
    version: '0.7.0',
    date: '2026-02-08',
    tag: 'feature',
    title: 'Secrets Management',
    items: [
      'CRUD UI for managing environment secrets (Settings > Secrets tab)',
      'Secrets stored per-user in KV, injected as env vars into every session',
      'API never returns full values — only name + last-4-char hint',
      'Reserved names blocked (CLAUDE_CODE_OAUTH_TOKEN, PATH, etc.)',
      'Max 50 secrets per user, 10KB per value',
    ],
  },
  {
    version: '0.6.0',
    date: '2026-02-08',
    tag: 'feature',
    title: 'Landing Page, Pricing, and Login',
    items: [
      'Marketing landing page with hero, features, and how-it-works sections',
      'Pricing page with Pro tier at $20/month and FAQ',
      'Presentational login page linking to setup-token auth flow',
      'SPA moved to /app subdirectory with Vite base path',
      'Monorepo build: Astro landing + Vite SPA merged into single dist/',
    ],
  },
  {
    version: '0.5.0',
    date: '2026-02-08',
    tag: 'feature',
    title: 'Mobile Powerhouse — iPad, Theme, Haptics, Settings',
    items: [
      'Touch-friendly copy buttons: always visible on touch devices (no hover needed)',
      'iPad layout: tablet tier with 2-panel default, auto-collapsed file tree',
      'Cmd+Enter to send messages (iPad keyboard users)',
      'Dark/light theme toggle with full CSS variable system',
      'Haptic feedback on send, copy, and swipe gestures (Vibration API)',
      'Pull-to-refresh in mobile chat view',
      'Pinch-to-zoom in editor (10-24px) and terminal (9-22px) with persistence',
      'Commands tab: manage slash commands in sandbox ~/.claude/commands/',
      'MCP tab: manage MCP servers in sandbox ~/.claude.json',
      'PWA raster icons (192px, 512px) and screenshot entries in manifest',
      'Keyboard shortcuts guide expanded in settings',
    ],
  },
  {
    version: '0.4.6',
    date: '2026-02-07',
    tag: 'feature',
    title: 'Debug Panel + Image Pasting',
    items: [
      'Debug panel: floating Dev button captures API errors, stream failures, and uncaught exceptions',
      'Debug log: expandable entries with category badges, timestamps, and detail JSON',
      'Image pasting: Cmd+V images into chat, auto-uploads to sandbox for Claude to analyze',
      'Image preview strip with thumbnails and remove buttons below prompt input',
      'User messages show image attachment badges inline',
      'Backend upload-base64 route for binary file uploads to sandbox',
      'Enable debug panel: localStorage.setItem("vf_debug", "1")',
    ],
  },
  {
    version: '0.4.5',
    date: '2026-02-07',
    tag: 'feature',
    title: 'Session Persistence + File Explorer Expand/Collapse',
    items: [
      'Session survives page refresh: auto-restores last active session with chat, files, and git status',
      'Expand all / collapse all buttons in file explorer toolbar',
      'Expand all skips node_modules, .git, .next, dist, .cache',
      'Improved download icon visibility on selected file rows',
    ],
  },
  {
    version: '0.4.4',
    date: '2026-02-07',
    tag: 'feature',
    title: 'File Upload + Download/Export',
    items: [
      'Upload files: drag-and-drop or file picker, uploads to current directory',
      'Download individual files from file explorer (hover to reveal button)',
      'Download workspace as .tar.gz archive (excludes node_modules and .git)',
      'Upload spinner and drag overlay with visual feedback',
    ],
  },
  {
    version: '0.4.3',
    date: '2026-02-07',
    tag: 'feature',
    title: 'Session Management + Auto-Reconnect',
    items: [
      'Session naming: rename sessions inline from welcome screen or header',
      'Auto-reconnect: detects wake-from-sleep, resets stuck streams, wakes sandbox',
      'Session list: time-ago timestamps, status dots, show-all toggle',
      'Session name persisted to KV on create (was lost before)',
      'Cleaned up git repo URL display (strips https://github.com/ prefix)',
    ],
  },
  {
    version: '0.4.2',
    date: '2026-02-07',
    tag: 'fix',
    title: 'Clone Repo + File Explorer Navigation',
    items: [
      'Fixed clone repo: removed double-clone that caused /workspace conflict',
      'Branch parameter now passed through session creation',
      'File explorer: breadcrumb navigation with home button',
      'File explorer: ".." parent directory entry for going back',
      'File tree renders nested directories recursively with cached children',
      'Code review fixes: clipboard error handling, download timing, streaming flags',
    ],
  },
  {
    version: '0.4.1',
    date: '2026-02-07',
    tag: 'feature',
    title: 'Artifact + Chain of Thought Components',
    items: [
      'Artifact blocks: code files render with copy, download, and run actions',
      'Chain of thought: multi-step reasoning timeline with status indicators',
      'Auto-detect Write/Edit tool results and promote to artifact display',
      'Collapsible step content with search result badges',
    ],
  },
  {
    version: '0.4.0',
    date: '2026-02-07',
    tag: 'feature',
    title: 'UI Upgrade — AI Elements-Inspired Chat',
    items: [
      'Redesigned chat: edge-aligned messages (no avatar bubbles), cleaner spacing',
      'Enhanced tool call blocks with animated expand/collapse and live duration timer',
      'Code blocks with line numbers, filename headers, and line count display',
      'Collapsible reasoning/thinking blocks with shimmer animation',
      'Upgraded prompt input with pill-style border, ArrowUp send, inline stop button',
      'New shimmer skeleton streaming indicator with pulse animation',
      'File change blocks for create/edit/delete operations',
      'Reasoning part type support in streaming pipeline',
    ],
  },
  {
    version: '0.3.0',
    date: '2026-02-07',
    tag: 'feature',
    title: 'SDK Fix + Clone Repo + IDE Polish',
    items: [
      'Fixed SDK crash: added IS_SANDBOX, env spread, and continue flag',
      'System prompt enforces /workspace for file creation (no more /tmp)',
      'Clone Repo modal: import any Git repo into a new workspace',
      'Collapsible panels with Cmd+1/2/3 keyboard shortcuts',
      'Warp-inspired resize handles with grip dots and glow effects',
      'Panel headers with collapse/expand buttons and shortcut hints',
    ],
  },
  {
    version: '0.2.0',
    date: '2026-02-07',
    tag: 'feature',
    title: 'Tool Execution + Rich Chat',
    items: [
      'Claude can now create files, run commands, and edit code in the sandbox',
      'Rich chat UI with markdown rendering, syntax highlighting, and tool display',
      'Streaming SDK responses with structured tool-start/tool-result events',
      'Increased chat timeout from 60s to 5 min for complex tool operations',
    ],
  },
  {
    version: '0.1.2',
    date: '2026-02-06',
    tag: 'feature',
    title: 'Terminal Streaming + Session Continuity',
    items: [
      'Stream Claude CLI responses in the terminal via SSE',
      'Auto-prompt wrapping: plain text becomes `claude -p "..."`',
      'Session continuity with SDK resume parameter',
      'Hybrid SDK terminal with session management UI',
    ],
  },
  {
    version: '0.1.1',
    date: '2026-02-05',
    tag: 'fix',
    title: 'Auth + Sandbox Stability',
    items: [
      'Setup-token auth flow (replaced broken OAuth)',
      'Claude token injected as persistent sandbox env var',
      'Sandbox termination and timeout fixes',
      'Mobile-optimized layout with PWA support',
    ],
  },
  {
    version: '0.1.0',
    date: '2026-02-04',
    tag: 'feature',
    title: 'Initial Release',
    items: [
      'Web-based Claude Code IDE on Cloudflare Sandboxes',
      'File explorer, Monaco editor, xterm.js terminal',
      'Resizable panels (desktop) and tab navigation (mobile)',
      'R2 bucket for file persistence',
    ],
  },
];
