// Single source of truth for app version and changelog
// Update this file when releasing new versions

export const APP_VERSION = '0.17.0';

export interface ChangelogEntry {
  readonly version: string;
  readonly date: string;
  readonly tag: 'feature' | 'fix' | 'security' | 'breaking';
  readonly title: string;
  readonly items: readonly string[];
}

export const CHANGELOG: readonly ChangelogEntry[] = [
  {
    version: '0.17.0',
    date: '2026-02-15',
    tag: 'feature',
    title: 'Semantic Search — Find Code by Meaning',
    items: [
      'Semantic search: ask "where is auth logic?" and find files by concept, not just text',
      'Google text-embedding-004 indexes up to 500 workspace files automatically on session create',
      'semanticSearch tool in Quick Chat: AI proactively searches codebase for conceptual queries',
      'Source citations: file pills with relevance scores appear after semantic search results',
      'Click any source pill to open the file directly in the editor',
      'Embedding status badge in Quick Chat header: shows indexing progress and file count',
      'Re-index button to rebuild embeddings after file changes',
      'Requires Gemini API key — gracefully hidden when not configured',
    ],
  },
  {
    version: '0.16.0',
    date: '2026-02-15',
    tag: 'feature',
    title: 'Chat Visual Overhaul + DevTools',
    items: [
      'LaTeX math rendering: inline ($E=mc^2$) and block ($$) via KaTeX',
      'Streaming markdown hardening: unclosed code fences, bold, italic, and tables render correctly mid-stream',
      'Message avatars: Bot/User icons with streaming pulse animation on assistant avatar',
      'Relative timestamps on messages ("2m ago") with 30s auto-refresh',
      'Left border accent on assistant messages for visual hierarchy',
      'Stop streaming button: abort mid-stream and keep partial response',
      'Thumbs up/down feedback on messages (persisted to localStorage)',
      'Task Plan view: agent workflows with 3+ tool calls show a grouped phase timeline (Exploring, Implementing, Testing, Committing)',
      'DevTools Stream tab: real-time event log with type filter',
      'DevTools Tokens tab: per-message token estimates with input/output breakdown',
      'DevTools Latency tab: TTFT, stream duration, and tokens/sec gradient meters',
      'Code block shimmer skeleton during streaming (replaces blank block)',
    ],
  },
  {
    version: '0.15.1',
    date: '2026-02-15',
    tag: 'feature',
    title: 'Keyboard Shortcuts + Panel Persistence + Wiki',
    items: [
      'Settings now shows all 15 keyboard shortcuts across 5 groups (was 7)',
      'New AI Tools shortcut group: Quick Chat, Code Transform, Code Analysis, Commit Message',
      'Panel sizes persist across page reloads — resize once, keep your layout',
      'Cmd+Shift+0 resets panels to default (or your saved custom default)',
      'Panel Layout card in Settings: visual size preview with Save/Reset buttons',
      'Wiki tab in Dev Panel: documents what each VaporForge surface can do',
    ],
  },
  {
    version: '0.15.0',
    date: '2026-02-15',
    tag: 'feature',
    title: 'Tool-Calling Agent for Quick Chat',
    items: [
      'Quick Chat now acts as a mini-agent when a sandbox session is active',
      'AI can read files, list directories, search code, and run commands in your sandbox',
      'Run Command requires explicit approval before execution (human-in-the-loop)',
      'Tool invocations displayed as collapsible cards with state badges (running, done, error, denied)',
      'Agent mode indicator in Quick Chat header when sandbox tools are available',
      'Multi-step tool chains: AI can call up to 10 tools per message to complete complex tasks',
    ],
  },
  {
    version: '0.14.2',
    date: '2026-02-14',
    tag: 'feature',
    title: 'Quick Chat — AI SDK useChat Migration',
    items: [
      'QuickChatPanel rewritten with AI SDK v6 useChat hook and DefaultChatTransport',
      'Backend stream endpoint returns UIMessageStreamResponse for native useChat consumption',
      'Message format upgraded to UIMessage parts[] (text, reasoning) with backward-compatible parsing',
      'Local input state replaces useChat-managed input for direct control',
      'Removed legacy streamQuickChat SSE generator — all streaming now handled by AI SDK transport',
      'Fixed maxTokens → maxOutputTokens rename across quickchat and transform endpoints',
    ],
  },
  {
    version: '0.14.1',
    date: '2026-02-14',
    tag: 'feature',
    title: 'Chat Performance — Normalized State + Memoized Messages',
    items: [
      'Normalized message state: messages stored in Record<id, Message> + ordered ID array for O(1) lookup',
      'Granular Zustand selectors: streaming updates no longer re-render historical messages',
      'React.memo on MemoizedMessageItem: each message only re-renders when its own data changes',
      'Isolated StreamingMessage component: subscribes only to streaming state, decoupled from message list',
      'MessageContent wrapped in React.memo for nested render isolation',
      'useMessage(id) / useMessageIds() / useMessageCount() selector hooks for per-message subscriptions',
    ],
  },
  {
    version: '0.14.0',
    date: '2026-02-14',
    tag: 'feature',
    title: 'AI Elements Chat UX — Suggestion, Reasoning, Shimmer',
    items: [
      'Suggestion chips: reusable compound component (Suggestions + Suggestion) in main chat and Quick Chat empty states',
      'Reasoning upgrade: Radix Collapsible with auto-open on stream start, auto-close after stream end, duration timer ("Thought for Ns")',
      'Shimmer text effect: CSS gradient sweep animation on streaming status labels (Thinking, Reasoning, Writing)',
      'Collapsible animations: smooth height transitions via Radix CSS variables',
      'cn() utility: lightweight class name joiner for component styling',
      'AI Elements component library: new ui/src/components/ai-elements/ directory for adapted Vercel AI Elements',
    ],
  },
  {
    version: '0.13.1',
    date: '2026-02-14',
    tag: 'feature',
    title: 'Live Plugin Catalog + Custom Sources',
    items: [
      'Add Plugin from URL: paste any GitHub repo URL to discover and install plugins directly',
      'Custom Source Repos: add your own GitHub repos as browsable plugin sources (max 10)',
      'Dynamic source filters: sidebar shows custom sources with live plugin counts and remove buttons',
      'Custom source badge (green) on marketplace cards for user-added plugins',
      'Refresh Installed: re-fetch latest content from GitHub for all git-sourced plugins',
      'Right-side controls: close/exit buttons moved to right side of all headers for consistency',
    ],
  },
  {
    version: '0.13.0',
    date: '2026-02-15',
    tag: 'feature',
    title: 'Config Persistence — Never Lose Data Again',
    items: [
      'Auto-restore CLAUDE.md, plugins, MCP servers, and user configs after container recycle',
      'Sentinel stamp file detects missing config without expensive re-reads',
      'Sync-back: in-container CLAUDE.md edits persist to KV after each message',
      'Config Sync section in DevTools with stamp status and Force Re-sync button',
      'Toast notification when config is restored after container wake',
    ],
  },
  {
    version: '0.11.0',
    date: '2026-02-13',
    tag: 'feature',
    title: 'Structured Intelligence + Dev Changelog',
    items: [
      'Code Analysis panel: streamObject() with progressive complexity meter, severity-badged issues (Cmd+Shift+A)',
      'Smart Commit Message: generateObject() card with editable type/scope/subject/body and preview (Cmd+Shift+G)',
      'Test Results Parser: auto-detects Jest/Vitest/pytest/Mocha output with pass/fail/skip progress bar',
      'Stack Trace Parser: clickable frames, dimmed node_modules, opens file in editor',
      'Dev Changelog: full-page overlay with date-grouped commits, expandable details, search, and filter (Cmd+Shift+L)',
      'Build-time version script: git hash, date, and commit log generated at build time for edge runtime',
      'Version badge in SessionTabBar shows app version and build hash',
    ],
  },
  {
    version: '0.10.0',
    date: '2026-02-12',
    tag: 'feature',
    title: 'AI SDK Integration — Quick Chat + Code Transform',
    items: [
      'Quick Chat: instant AI chat without starting a sandbox (Cmd+Shift+Q)',
      'Multi-provider support: switch between Claude and Gemini models on the fly',
      'Code Transform: select code in editor, describe a change, get a diff view (Cmd+Shift+T)',
      'Provider availability guard: auto-selects configured provider, disables unavailable ones',
      'Chat history persisted in KV with 7-day TTL',
      'Dev Tools settings panel: build version tracking with client/server mismatch detection',
      'Fixed stale Gemini model IDs (preview models replaced with stable versions)',
    ],
  },
  {
    version: '0.9.6',
    date: '2026-02-12',
    tag: 'feature',
    title: 'Gemini AI Integration',
    items: [
      'Google Gemini available as an AI provider — Claude can delegate tasks to Gemini',
      'Three Gemini tools: quick_query (Flash), analyze_code (Pro), codebase_analysis (Pro+files)',
      'AI Providers settings tab: add API key, toggle provider, choose default model',
      'Gemini expert agent: use /agent:gemini-expert for full Gemini delegation mode',
      'Auto-retry with exponential backoff on rate limits (429) — handles free tier gracefully',
      'Zero-dependency MCP server runs inside the sandbox container',
      'Free tier: 1,000 requests/day with any personal Gmail account',
    ],
  },
  {
    version: '0.9.5',
    date: '2026-02-13',
    tag: 'feature',
    title: 'VaporFiles Manager + Copy MD Fix',
    items: [
      'VaporFiles tab in Settings: browse, upload, preview, and delete R2 files',
      'Image gallery with thumbnail grid and full-screen preview modal',
      'Drag-and-drop upload with visual drop zone indicator',
      'Copy shareable R2 URLs for any file (permanent, cached)',
      'Files persist across sessions — R2 storage is independent of sandboxes',
      'Copy MD now respects multi-select: copies all selected issues, not just current tab',
      'Header Copy MD button changes color and shows count when items selected',
      'Fixed file deletion bug: was passing ID without extension to R2',
    ],
  },
  {
    version: '0.9.4',
    date: '2026-02-09',
    tag: 'feature',
    title: 'Command Center + Plugin Refresh',
    items: [
      'Command Center settings tab: edit internal container rules for Claude SDK',
      'VF rules prepended to CLAUDE.md in every sandbox — Claude now knows its environment',
      'Default rules cover container awareness, MCP relay, secrets, and what NOT to do',
      'Reset to defaults button to restore original VF rules',
      'Plugin refresh endpoint: re-discover all git-sourced plugins from GitHub',
      'Refresh preserves user toggle states (enabled/disabled) while updating content',
      'Config injection order documented in Command Center UI',
    ],
  },
  {
    version: '0.9.3',
    date: '2026-02-09',
    tag: 'feature',
    title: 'Slash Commands + Plugin Pipeline Fix',
    items: [
      'Slash command autocomplete: type / in chat to see matching commands',
      'Rich built-in command templates for /review, /test, /docs, /refactor',
      'Plugin discover supports monorepo subpaths and root-level convention dirs',
      'Catalog toggle bug fixed: plugins no longer share URLs',
      'Marketplace install creates fallback commands from catalog metadata',
    ],
  },
  {
    version: '0.9.2',
    date: '2026-02-09',
    tag: 'feature',
    title: 'Warp-Style Layout Overhaul',
    items: [
      'Chat moved to center panel (55%), editor+terminal to right sidebar (30%)',
      'SessionTabBar: horizontal tabs with click, double-click rename, hover close',
      'Focus mode (Cmd+3): collapse both sidebars for full-screen chat',
      'Right panel auto-expands when file opened from file tree',
      'Delete All button for pending-delete sessions section',
    ],
  },
  {
    version: '0.9.1',
    date: '2026-02-09',
    tag: 'feature',
    title: 'Landing Page Visual Overhaul + 3-Tier Pricing',
    items: [
      '3-tier pricing: Free/$0, Pro/$20, Premium/$80 with feature highlights',
      'Compare table: VF Pro, VF Premium, Cursor, Codespaces, and Replit side-by-side',
      'Feature cards: bigger titles, gradient text, keyword pills, hover lift',
      'Premium tier numbers highlighted in cyan to show upgrade value',
      'Nav restyled: all links brighter, accent links in purple with separator',
      'FAQ brighter borders with hover glow, TechStack card-wrapped details',
    ],
  },
  {
    version: '0.9.0',
    date: '2026-02-09',
    tag: 'feature',
    title: 'Frontend MCP Relay',
    items: [
      'Connect local MCP servers to cloud SDK via WebSocket relay chain',
      'Relay proxy in container forwards JSON-RPC to local stdio servers',
      'Relay status indicator in header with connection state',
      'McpTab settings UI for adding/removing relay servers',
      'Session API extended with MCP relay config persistence',
    ],
  },
  {
    version: '0.8.0',
    date: '2026-02-09',
    tag: 'feature',
    title: 'MCP Persistence + Plugins System',
    items: [
      'MCP servers now persist — writes directly to ~/.claude.json in sandbox',
      'Plugins and Agents settings tab with visual agent-command connections',
      'iPad safe area fix, GitHub repo browser, and favorites list',
      'Add/remove buttons visible and usable on touch devices',
      'Favicon updated to match landing page logo',
    ],
  },
  {
    version: '0.7.1',
    date: '2026-02-08',
    tag: 'fix',
    title: 'Chat Persistence Fix',
    items: [
      'SDK stream endpoint now writes messages to KV for persistence',
      'User messages saved before stream, assistant messages saved after',
      'Chat history survives page refresh and session reconnect',
    ],
  },
  {
    version: '0.7.0',
    date: '2026-02-08',
    tag: 'feature',
    title: 'Secrets Management',
    items: [
      'CRUD UI for managing environment secrets (Settings > Secrets tab)',
      'Secrets stored per-user in KV, injected as env vars into every session',
      'API never returns full values — only name + last-4-char hint',
      'Reserved names blocked (CLAUDE_CODE_OAUTH_TOKEN, PATH, etc.)',
      'Max 50 secrets per user, 10KB per value',
    ],
  },
  {
    version: '0.6.0',
    date: '2026-02-08',
    tag: 'feature',
    title: 'Landing Page, Pricing, and Login',
    items: [
      'Marketing landing page with hero, features, and how-it-works sections',
      'Pricing page with Pro tier at $20/month and FAQ',
      'Presentational login page linking to setup-token auth flow',
      'SPA moved to /app subdirectory with Vite base path',
      'Monorepo build: Astro landing + Vite SPA merged into single dist/',
    ],
  },
  {
    version: '0.5.0',
    date: '2026-02-08',
    tag: 'feature',
    title: 'Mobile Powerhouse — iPad, Theme, Haptics, Settings',
    items: [
      'Touch-friendly copy buttons: always visible on touch devices (no hover needed)',
      'iPad layout: tablet tier with 2-panel default, auto-collapsed file tree',
      'Cmd+Enter to send messages (iPad keyboard users)',
      'Dark/light theme toggle with full CSS variable system',
      'Haptic feedback on send, copy, and swipe gestures (Vibration API)',
      'Pull-to-refresh in mobile chat view',
      'Pinch-to-zoom in editor (10-24px) and terminal (9-22px) with persistence',
      'Commands tab: manage slash commands in sandbox ~/.claude/commands/',
      'MCP tab: manage MCP servers in sandbox ~/.claude.json',
      'PWA raster icons (192px, 512px) and screenshot entries in manifest',
      'Keyboard shortcuts guide expanded in settings',
    ],
  },
  {
    version: '0.4.6',
    date: '2026-02-07',
    tag: 'feature',
    title: 'Debug Panel + Image Pasting',
    items: [
      'Debug panel: floating Dev button captures API errors, stream failures, and uncaught exceptions',
      'Debug log: expandable entries with category badges, timestamps, and detail JSON',
      'Image pasting: Cmd+V images into chat, auto-uploads to sandbox for Claude to analyze',
      'Image preview strip with thumbnails and remove buttons below prompt input',
      'User messages show image attachment badges inline',
      'Backend upload-base64 route for binary file uploads to sandbox',
      'Enable debug panel: localStorage.setItem("vf_debug", "1")',
    ],
  },
  {
    version: '0.4.5',
    date: '2026-02-07',
    tag: 'feature',
    title: 'Session Persistence + File Explorer Expand/Collapse',
    items: [
      'Session survives page refresh: auto-restores last active session with chat, files, and git status',
      'Expand all / collapse all buttons in file explorer toolbar',
      'Expand all skips node_modules, .git, .next, dist, .cache',
      'Improved download icon visibility on selected file rows',
    ],
  },
  {
    version: '0.4.4',
    date: '2026-02-07',
    tag: 'feature',
    title: 'File Upload + Download/Export',
    items: [
      'Upload files: drag-and-drop or file picker, uploads to current directory',
      'Download individual files from file explorer (hover to reveal button)',
      'Download workspace as .tar.gz archive (excludes node_modules and .git)',
      'Upload spinner and drag overlay with visual feedback',
    ],
  },
  {
    version: '0.4.3',
    date: '2026-02-07',
    tag: 'feature',
    title: 'Session Management + Auto-Reconnect',
    items: [
      'Session naming: rename sessions inline from welcome screen or header',
      'Auto-reconnect: detects wake-from-sleep, resets stuck streams, wakes sandbox',
      'Session list: time-ago timestamps, status dots, show-all toggle',
      'Session name persisted to KV on create (was lost before)',
      'Cleaned up git repo URL display (strips https://github.com/ prefix)',
    ],
  },
  {
    version: '0.4.2',
    date: '2026-02-07',
    tag: 'fix',
    title: 'Clone Repo + File Explorer Navigation',
    items: [
      'Fixed clone repo: removed double-clone that caused /workspace conflict',
      'Branch parameter now passed through session creation',
      'File explorer: breadcrumb navigation with home button',
      'File explorer: ".." parent directory entry for going back',
      'File tree renders nested directories recursively with cached children',
      'Code review fixes: clipboard error handling, download timing, streaming flags',
    ],
  },
  {
    version: '0.4.1',
    date: '2026-02-07',
    tag: 'feature',
    title: 'Artifact + Chain of Thought Components',
    items: [
      'Artifact blocks: code files render with copy, download, and run actions',
      'Chain of thought: multi-step reasoning timeline with status indicators',
      'Auto-detect Write/Edit tool results and promote to artifact display',
      'Collapsible step content with search result badges',
    ],
  },
  {
    version: '0.4.0',
    date: '2026-02-07',
    tag: 'feature',
    title: 'UI Upgrade — AI Elements-Inspired Chat',
    items: [
      'Redesigned chat: edge-aligned messages (no avatar bubbles), cleaner spacing',
      'Enhanced tool call blocks with animated expand/collapse and live duration timer',
      'Code blocks with line numbers, filename headers, and line count display',
      'Collapsible reasoning/thinking blocks with shimmer animation',
      'Upgraded prompt input with pill-style border, ArrowUp send, inline stop button',
      'New shimmer skeleton streaming indicator with pulse animation',
      'File change blocks for create/edit/delete operations',
      'Reasoning part type support in streaming pipeline',
    ],
  },
  {
    version: '0.3.0',
    date: '2026-02-07',
    tag: 'feature',
    title: 'SDK Fix + Clone Repo + IDE Polish',
    items: [
      'Fixed SDK crash: added IS_SANDBOX, env spread, and continue flag',
      'System prompt enforces /workspace for file creation (no more /tmp)',
      'Clone Repo modal: import any Git repo into a new workspace',
      'Collapsible panels with Cmd+1/2/3 keyboard shortcuts',
      'Warp-inspired resize handles with grip dots and glow effects',
      'Panel headers with collapse/expand buttons and shortcut hints',
    ],
  },
  {
    version: '0.2.0',
    date: '2026-02-07',
    tag: 'feature',
    title: 'Tool Execution + Rich Chat',
    items: [
      'Claude can now create files, run commands, and edit code in the sandbox',
      'Rich chat UI with markdown rendering, syntax highlighting, and tool display',
      'Streaming SDK responses with structured tool-start/tool-result events',
      'Increased chat timeout from 60s to 5 min for complex tool operations',
    ],
  },
  {
    version: '0.1.2',
    date: '2026-02-06',
    tag: 'feature',
    title: 'Terminal Streaming + Session Continuity',
    items: [
      'Stream Claude CLI responses in the terminal via SSE',
      'Auto-prompt wrapping: plain text becomes `claude -p "..."`',
      'Session continuity with SDK resume parameter',
      'Hybrid SDK terminal with session management UI',
    ],
  },
  {
    version: '0.1.1',
    date: '2026-02-05',
    tag: 'fix',
    title: 'Auth + Sandbox Stability',
    items: [
      'Setup-token auth flow (replaced broken OAuth)',
      'Claude token injected as persistent sandbox env var',
      'Sandbox termination and timeout fixes',
      'Mobile-optimized layout with PWA support',
    ],
  },
  {
    version: '0.1.0',
    date: '2026-02-04',
    tag: 'feature',
    title: 'Initial Release',
    items: [
      'Web-based Claude Code IDE on Cloudflare Sandboxes',
      'File explorer, Monaco editor, xterm.js terminal',
      'Resizable panels (desktop) and tab navigation (mobile)',
      'R2 bucket for file persistence',
    ],
  },
];
